/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/
#include "pdm_pcm_definitions.h"

#if !USE_RT1050_EVKB

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_B0_04 (coord C8), LCDIF_D0/BT_CFG[0] */
#define BOARD_INITPINS_LCDIF_D0_GPIO                                       GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_LCDIF_D0_PORT                                       GPIO2   /*!< PORT device name: GPIO2 */
#define BOARD_INITPINS_LCDIF_D0_GPIO_PIN                                      4U   /*!< GPIO2 pin index: 4 */
#define BOARD_INITPINS_LCDIF_D0_PIN_NAME                              GPIO_B0_04   /*!< Pin name */
#define BOARD_INITPINS_LCDIF_D0_LABEL                       "LCDIF_D0/BT_CFG[0]"   /*!< Label */
#define BOARD_INITPINS_LCDIF_D0_NAME                                  "LCDIF_D0"   /*!< Identifier name */
#define BOARD_INITPINS_LCDIF_D0_DIRECTION                kPIN_MUX_DirectionInput   /*!< Direction */

/* GPIO_B0_09 (coord C9), LCDIF_D5/BT_CFG[5] */
#define BOARD_INITPINS_LCDIF_D5_GPIO                                       GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_LCDIF_D5_PORT                                       GPIO2   /*!< PORT device name: GPIO2 */
#define BOARD_INITPINS_LCDIF_D5_GPIO_PIN                                      9U   /*!< GPIO2 pin index: 9 */
#define BOARD_INITPINS_LCDIF_D5_PIN_NAME                              GPIO_B0_09   /*!< Pin name */
#define BOARD_INITPINS_LCDIF_D5_LABEL                       "LCDIF_D5/BT_CFG[5]"   /*!< Label */
#define BOARD_INITPINS_LCDIF_D5_NAME                                  "LCDIF_D5"   /*!< Identifier name */
#define BOARD_INITPINS_LCDIF_D5_DIRECTION                kPIN_MUX_DirectionInput   /*!< Direction */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/* GPIO_B0_11 (coord A10), LCDIF_D7/BT_CFG[7] */
#define BOARD_INITMICROPHONE_LCDIF_D7_PERIPHERAL                            SAI1   /*!< Device name: SAI1 */
#define BOARD_INITMICROPHONE_LCDIF_D7_SIGNAL                        sai_tx_data2   /*!< SAI1 signal: sai_tx_data2 */
#define BOARD_INITMICROPHONE_LCDIF_D7_PIN_NAME                        GPIO_B0_11   /*!< Pin name */
#define BOARD_INITMICROPHONE_LCDIF_D7_LABEL                 "LCDIF_D7/BT_CFG[7]"   /*!< Label */
#define BOARD_INITMICROPHONE_LCDIF_D7_NAME                            "LCDIF_D7"   /*!< Identifier name */

/* GPIO_B1_00 (coord A11), LCDIF_D12 */
#define BOARD_INITMICROPHONE_LCDIF_D12_PERIPHERAL                           SAI1   /*!< Device name: SAI1 */
#define BOARD_INITMICROPHONE_LCDIF_D12_SIGNAL                       sai_rx_data0   /*!< SAI1 signal: sai_rx_data0 */
#define BOARD_INITMICROPHONE_LCDIF_D12_PIN_NAME                       GPIO_B1_00   /*!< Pin name */
#define BOARD_INITMICROPHONE_LCDIF_D12_LABEL                         "LCDIF_D12"   /*!< Label */
#define BOARD_INITMICROPHONE_LCDIF_D12_NAME                          "LCDIF_D12"   /*!< Identifier name */

/* GPIO_EMC_39 (coord B7), SEMC_DQS */
#define BOARD_INITMICROPHONE_SEMC_DQS_PERIPHERAL                            SAI3   /*!< Device name: SAI3 */
#define BOARD_INITMICROPHONE_SEMC_DQS_SIGNAL                         sai_tx_sync   /*!< SAI3 signal: sai_tx_sync */
#define BOARD_INITMICROPHONE_SEMC_DQS_PIN_NAME                       GPIO_EMC_39   /*!< Pin name */
#define BOARD_INITMICROPHONE_SEMC_DQS_LABEL                           "SEMC_DQS"   /*!< Label */
#define BOARD_INITMICROPHONE_SEMC_DQS_NAME                            "SEMC_DQS"   /*!< Identifier name */

/* GPIO_B0_12 (coord C10), LCDIF_D8/BT_CFG[8] */
#define BOARD_INITMICROPHONE_LCDIF_D8_PERIPHERAL                            SAI1   /*!< Device name: SAI1 */
#define BOARD_INITMICROPHONE_LCDIF_D8_SIGNAL                        sai_tx_data1   /*!< SAI1 signal: sai_tx_data1 */
#define BOARD_INITMICROPHONE_LCDIF_D8_PIN_NAME                        GPIO_B0_12   /*!< Pin name */
#define BOARD_INITMICROPHONE_LCDIF_D8_LABEL                 "LCDIF_D8/BT_CFG[8]"   /*!< Label */
#define BOARD_INITMICROPHONE_LCDIF_D8_NAME                            "LCDIF_D8"   /*!< Identifier name */

/* GPIO_EMC_36 (coord C3), SEMC_D14 */
#define BOARD_INITMICROPHONE_SEMC_D14_PERIPHERAL                            SAI3   /*!< Device name: SAI3 */
#define BOARD_INITMICROPHONE_SEMC_D14_SIGNAL                         sai_tx_data   /*!< SAI3 signal: sai_tx_data */
#define BOARD_INITMICROPHONE_SEMC_D14_PIN_NAME                       GPIO_EMC_36   /*!< Pin name */
#define BOARD_INITMICROPHONE_SEMC_D14_LABEL                           "SEMC_D14"   /*!< Label */
#define BOARD_INITMICROPHONE_SEMC_D14_NAME                            "SEMC_D14"   /*!< Identifier name */

/* GPIO_EMC_33 (coord C4), SEMC_D11 */
#define BOARD_INITMICROPHONE_SEMC_D11_PERIPHERAL                            SAI3   /*!< Device name: SAI3 */
#define BOARD_INITMICROPHONE_SEMC_D11_SIGNAL                         sai_rx_data   /*!< SAI3 signal: sai_rx_data */
#define BOARD_INITMICROPHONE_SEMC_D11_PIN_NAME                       GPIO_EMC_33   /*!< Pin name */
#define BOARD_INITMICROPHONE_SEMC_D11_LABEL                           "SEMC_D11"   /*!< Label */
#define BOARD_INITMICROPHONE_SEMC_D11_NAME                            "SEMC_D11"   /*!< Identifier name */

/* GPIO_B0_13 (coord D10), LCDIF_D9/BT_CFG[9] */
#define BOARD_INITMICROPHONE_LCDIF_D9_PERIPHERAL                            SAI1   /*!< Device name: SAI1 */
#define BOARD_INITMICROPHONE_LCDIF_D9_SIGNAL                            sai_mclk   /*!< SAI1 signal: sai_mclk */
#define BOARD_INITMICROPHONE_LCDIF_D9_PIN_NAME                        GPIO_B0_13   /*!< Pin name */
#define BOARD_INITMICROPHONE_LCDIF_D9_LABEL                 "LCDIF_D9/BT_CFG[9]"   /*!< Label */
#define BOARD_INITMICROPHONE_LCDIF_D9_NAME                            "LCDIF_D9"   /*!< Identifier name */

/* GPIO_B0_15 (coord E11), LCDIF_D11/BT_CFG[11] */
#define BOARD_INITMICROPHONE_LCDIF_D11_PERIPHERAL                           SAI1   /*!< Device name: SAI1 */
#define BOARD_INITMICROPHONE_LCDIF_D11_SIGNAL                        sai_rx_bclk   /*!< SAI1 signal: sai_rx_bclk */
#define BOARD_INITMICROPHONE_LCDIF_D11_PIN_NAME                       GPIO_B0_15   /*!< Pin name */
#define BOARD_INITMICROPHONE_LCDIF_D11_LABEL              "LCDIF_D11/BT_CFG[11]"   /*!< Label */
#define BOARD_INITMICROPHONE_LCDIF_D11_NAME                          "LCDIF_D11"   /*!< Identifier name */

/* GPIO_B0_10 (coord D9), LCDIF_D6/BT_CFG[6] */
#define BOARD_INITMICROPHONE_LCDIF_D6_PERIPHERAL                            SAI1   /*!< Device name: SAI1 */
#define BOARD_INITMICROPHONE_LCDIF_D6_SIGNAL                        sai_tx_data3   /*!< SAI1 signal: sai_tx_data3 */
#define BOARD_INITMICROPHONE_LCDIF_D6_PIN_NAME                        GPIO_B0_10   /*!< Pin name */
#define BOARD_INITMICROPHONE_LCDIF_D6_LABEL                 "LCDIF_D6/BT_CFG[6]"   /*!< Label */
#define BOARD_INITMICROPHONE_LCDIF_D6_NAME                            "LCDIF_D6"   /*!< Identifier name */

/* GPIO_B0_14 (coord E10), LCDIF_D10/BT_CFG[10] */
#define BOARD_INITMICROPHONE_LCDIF_D10_PERIPHERAL                           SAI1   /*!< Device name: SAI1 */
#define BOARD_INITMICROPHONE_LCDIF_D10_SIGNAL                        sai_rx_sync   /*!< SAI1 signal: sai_rx_sync */
#define BOARD_INITMICROPHONE_LCDIF_D10_PIN_NAME                       GPIO_B0_14   /*!< Pin name */
#define BOARD_INITMICROPHONE_LCDIF_D10_LABEL              "LCDIF_D10/BT_CFG[10]"   /*!< Label */
#define BOARD_INITMICROPHONE_LCDIF_D10_NAME                          "LCDIF_D10"   /*!< Identifier name */

/* GPIO_EMC_10 (coord G1), SEMC_A1 */
#define BOARD_INITMICROPHONE_SEMC_A1_PERIPHERAL                             SAI2   /*!< Device name: SAI2 */
#define BOARD_INITMICROPHONE_SEMC_A1_SIGNAL                          sai_rx_bclk   /*!< SAI2 signal: sai_rx_bclk */
#define BOARD_INITMICROPHONE_SEMC_A1_PIN_NAME                        GPIO_EMC_10   /*!< Pin name */
#define BOARD_INITMICROPHONE_SEMC_A1_LABEL                             "SEMC_A1"   /*!< Label */
#define BOARD_INITMICROPHONE_SEMC_A1_NAME                              "SEMC_A1"   /*!< Identifier name */

/* GPIO_EMC_37 (coord E4), SEMC_D15 */
#define BOARD_INITMICROPHONE_SEMC_D15_PERIPHERAL                            SAI3   /*!< Device name: SAI3 */
#define BOARD_INITMICROPHONE_SEMC_D15_SIGNAL                            sai_mclk   /*!< SAI3 signal: sai_mclk */
#define BOARD_INITMICROPHONE_SEMC_D15_PIN_NAME                       GPIO_EMC_37   /*!< Pin name */
#define BOARD_INITMICROPHONE_SEMC_D15_LABEL                           "SEMC_D15"   /*!< Label */
#define BOARD_INITMICROPHONE_SEMC_D15_NAME                            "SEMC_D15"   /*!< Identifier name */

/* GPIO_EMC_38 (coord D6), SEMC_DM1 */
#define BOARD_INITMICROPHONE_SEMC_DM1_PERIPHERAL                            SAI3   /*!< Device name: SAI3 */
#define BOARD_INITMICROPHONE_SEMC_DM1_SIGNAL                         sai_tx_bclk   /*!< SAI3 signal: sai_tx_bclk */
#define BOARD_INITMICROPHONE_SEMC_DM1_PIN_NAME                       GPIO_EMC_38   /*!< Pin name */
#define BOARD_INITMICROPHONE_SEMC_DM1_LABEL                           "SEMC_DM1"   /*!< Label */
#define BOARD_INITMICROPHONE_SEMC_DM1_NAME                            "SEMC_DM1"   /*!< Identifier name */

/* GPIO_AD_B1_11 (coord J13), SAI1_RX_BCLK/CSI_D6/J35[7]/J23[2] */
#define BOARD_INITMICROPHONE_CSI_D6_GPIO                                   GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITMICROPHONE_CSI_D6_PORT                                   GPIO1   /*!< PORT device name: GPIO1 */
#define BOARD_INITMICROPHONE_CSI_D6_GPIO_PIN                                 27U   /*!< GPIO1 pin index: 27 */
#define BOARD_INITMICROPHONE_CSI_D6_PIN_NAME                       GPIO_AD_B1_11   /*!< Pin name */
#define BOARD_INITMICROPHONE_CSI_D6_LABEL    "SAI1_RX_BCLK/CSI_D6/J35[7]/J23[2]"   /*!< Label */
#define BOARD_INITMICROPHONE_CSI_D6_NAME                                "CSI_D6"   /*!< Identifier name */

/* GPIO_AD_B1_14 (coord G12), SAI1_TX_BCLK/CSI_D3/J35[4]/U13[12] */
#define BOARD_INITMICROPHONE_CSI_D3_GPIO                                   GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITMICROPHONE_CSI_D3_PORT                                   GPIO1   /*!< PORT device name: GPIO1 */
#define BOARD_INITMICROPHONE_CSI_D3_GPIO_PIN                                 30U   /*!< GPIO1 pin index: 30 */
#define BOARD_INITMICROPHONE_CSI_D3_PIN_NAME                       GPIO_AD_B1_14   /*!< Pin name */
#define BOARD_INITMICROPHONE_CSI_D3_LABEL   "SAI1_TX_BCLK/CSI_D3/J35[4]/U13[12]"   /*!< Label */
#define BOARD_INITMICROPHONE_CSI_D3_NAME                                "CSI_D3"   /*!< Identifier name */

/* GPIO_AD_B1_03 (coord M12), SPDIF_IN/J22[8] */
#define BOARD_INITMICROPHONE_SPDIF_IN_GPIO                                 GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITMICROPHONE_SPDIF_IN_PORT                                 GPIO1   /*!< PORT device name: GPIO1 */
#define BOARD_INITMICROPHONE_SPDIF_IN_GPIO_PIN                               19U   /*!< GPIO1 pin index: 19 */
#define BOARD_INITMICROPHONE_SPDIF_IN_PIN_NAME                     GPIO_AD_B1_03   /*!< Pin name */
#define BOARD_INITMICROPHONE_SPDIF_IN_LABEL                    "SPDIF_IN/J22[8]"   /*!< Label */
#define BOARD_INITMICROPHONE_SPDIF_IN_NAME                            "SPDIF_IN"   /*!< Identifier name */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitMicrophone(void);

/* GPIO_B1_06 (coord C12), ENET_CRS_DV */
#define BOARD_INITETHERNET_ENET_CRS_DV_PERIPHERAL                           ENET   /*!< Device name: ENET */
#define BOARD_INITETHERNET_ENET_CRS_DV_SIGNAL                         enet_rx_en   /*!< ENET signal: enet_rx_en */
#define BOARD_INITETHERNET_ENET_CRS_DV_PIN_NAME                       GPIO_B1_06   /*!< Pin name */
#define BOARD_INITETHERNET_ENET_CRS_DV_LABEL                       "ENET_CRS_DV"   /*!< Label */
#define BOARD_INITETHERNET_ENET_CRS_DV_NAME                        "ENET_CRS_DV"   /*!< Identifier name */

/* GPIO_EMC_40 (coord A7), ENET_MDC */
#define BOARD_INITETHERNET_ENET_MDC_PERIPHERAL                              ENET   /*!< Device name: ENET */
#define BOARD_INITETHERNET_ENET_MDC_SIGNAL                              enet_mdc   /*!< ENET signal: enet_mdc */
#define BOARD_INITETHERNET_ENET_MDC_PIN_NAME                         GPIO_EMC_40   /*!< Pin name */
#define BOARD_INITETHERNET_ENET_MDC_LABEL                             "ENET_MDC"   /*!< Label */
#define BOARD_INITETHERNET_ENET_MDC_NAME                              "ENET_MDC"   /*!< Identifier name */

/* GPIO_EMC_41 (coord C7), ENET_MDIO */
#define BOARD_INITETHERNET_ENET_MDIO_PERIPHERAL                             ENET   /*!< Device name: ENET */
#define BOARD_INITETHERNET_ENET_MDIO_SIGNAL                            enet_mdio   /*!< ENET signal: enet_mdio */
#define BOARD_INITETHERNET_ENET_MDIO_PIN_NAME                        GPIO_EMC_41   /*!< Pin name */
#define BOARD_INITETHERNET_ENET_MDIO_LABEL                           "ENET_MDIO"   /*!< Label */
#define BOARD_INITETHERNET_ENET_MDIO_NAME                            "ENET_MDIO"   /*!< Identifier name */

/* GPIO_B1_10 (coord B13), ENET_TX_CLK */
#define BOARD_INITETHERNET_ENET_TX_CLK_PERIPHERAL                           ENET   /*!< Device name: ENET */
#define BOARD_INITETHERNET_ENET_TX_CLK_SIGNAL                       enet_ref_clk   /*!< ENET signal: enet_ref_clk */
#define BOARD_INITETHERNET_ENET_TX_CLK_PIN_NAME                       GPIO_B1_10   /*!< Pin name */
#define BOARD_INITETHERNET_ENET_TX_CLK_LABEL                       "ENET_TX_CLK"   /*!< Label */
#define BOARD_INITETHERNET_ENET_TX_CLK_NAME                        "ENET_TX_CLK"   /*!< Identifier name */

/* GPIO_B1_04 (coord E12), ENET_RXD0 */
#define BOARD_INITETHERNET_ENET_RXD0_PERIPHERAL                             ENET   /*!< Device name: ENET */
#define BOARD_INITETHERNET_ENET_RXD0_SIGNAL                         enet_rx_data   /*!< ENET signal: enet_rx_data */
#define BOARD_INITETHERNET_ENET_RXD0_CHANNEL                                  0U   /*!< ENET enet_rx_data channel: 0 */
#define BOARD_INITETHERNET_ENET_RXD0_PIN_NAME                         GPIO_B1_04   /*!< Pin name */
#define BOARD_INITETHERNET_ENET_RXD0_LABEL                           "ENET_RXD0"   /*!< Label */
#define BOARD_INITETHERNET_ENET_RXD0_NAME                            "ENET_RXD0"   /*!< Identifier name */

/* GPIO_B1_05 (coord D12), ENET_RXD1 */
#define BOARD_INITETHERNET_ENET_RXD1_PERIPHERAL                             ENET   /*!< Device name: ENET */
#define BOARD_INITETHERNET_ENET_RXD1_SIGNAL                         enet_rx_data   /*!< ENET signal: enet_rx_data */
#define BOARD_INITETHERNET_ENET_RXD1_CHANNEL                                  1U   /*!< ENET enet_rx_data channel: 1 */
#define BOARD_INITETHERNET_ENET_RXD1_PIN_NAME                         GPIO_B1_05   /*!< Pin name */
#define BOARD_INITETHERNET_ENET_RXD1_LABEL                           "ENET_RXD1"   /*!< Label */
#define BOARD_INITETHERNET_ENET_RXD1_NAME                            "ENET_RXD1"   /*!< Identifier name */

/* GPIO_B1_07 (coord B12), ENET_TXD0 */
#define BOARD_INITETHERNET_ENET_TXD0_PERIPHERAL                             ENET   /*!< Device name: ENET */
#define BOARD_INITETHERNET_ENET_TXD0_SIGNAL                         enet_tx_data   /*!< ENET signal: enet_tx_data */
#define BOARD_INITETHERNET_ENET_TXD0_CHANNEL                                  0U   /*!< ENET enet_tx_data channel: 0 */
#define BOARD_INITETHERNET_ENET_TXD0_PIN_NAME                         GPIO_B1_07   /*!< Pin name */
#define BOARD_INITETHERNET_ENET_TXD0_LABEL                           "ENET_TXD0"   /*!< Label */
#define BOARD_INITETHERNET_ENET_TXD0_NAME                            "ENET_TXD0"   /*!< Identifier name */

/* GPIO_B1_08 (coord A12), ENET_TXD1 */
#define BOARD_INITETHERNET_ENET_TXD1_PERIPHERAL                             ENET   /*!< Device name: ENET */
#define BOARD_INITETHERNET_ENET_TXD1_SIGNAL                         enet_tx_data   /*!< ENET signal: enet_tx_data */
#define BOARD_INITETHERNET_ENET_TXD1_CHANNEL                                  1U   /*!< ENET enet_tx_data channel: 1 */
#define BOARD_INITETHERNET_ENET_TXD1_PIN_NAME                         GPIO_B1_08   /*!< Pin name */
#define BOARD_INITETHERNET_ENET_TXD1_LABEL                           "ENET_TXD1"   /*!< Label */
#define BOARD_INITETHERNET_ENET_TXD1_NAME                            "ENET_TXD1"   /*!< Identifier name */

/* GPIO_B1_09 (coord A13), ENET_TXEN */
#define BOARD_INITETHERNET_ENET_TXEN_PERIPHERAL                             ENET   /*!< Device name: ENET */
#define BOARD_INITETHERNET_ENET_TXEN_SIGNAL                           enet_tx_en   /*!< ENET signal: enet_tx_en */
#define BOARD_INITETHERNET_ENET_TXEN_PIN_NAME                         GPIO_B1_09   /*!< Pin name */
#define BOARD_INITETHERNET_ENET_TXEN_LABEL                           "ENET_TXEN"   /*!< Label */
#define BOARD_INITETHERNET_ENET_TXEN_NAME                            "ENET_TXEN"   /*!< Identifier name */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitEthernet(void);

/* GPIO_EMC_06 (coord H5), SEMC_D6 */
#define BOARD_INITFLASH_SEMC_D6_PERIPHERAL                                  PWM2   /*!< Device name: PWM2 */
#define BOARD_INITFLASH_SEMC_D6_SIGNAL                                         A   /*!< PWM2 signal: A */
#define BOARD_INITFLASH_SEMC_D6_CHANNEL                                       0U   /*!< PWM2 A channel: 0 */
#define BOARD_INITFLASH_SEMC_D6_PIN_NAME                             GPIO_EMC_06   /*!< Pin name */
#define BOARD_INITFLASH_SEMC_D6_LABEL                                  "SEMC_D6"   /*!< Label */
#define BOARD_INITFLASH_SEMC_D6_NAME                                   "SEMC_D6"   /*!< Identifier name */

/* GPIO_EMC_08 (coord H3), SEMC_DM0 */
#define BOARD_INITFLASH_SEMC_DM0_PERIPHERAL                                 PWM2   /*!< Device name: PWM2 */
#define BOARD_INITFLASH_SEMC_DM0_SIGNAL                                        A   /*!< PWM2 signal: A */
#define BOARD_INITFLASH_SEMC_DM0_CHANNEL                                      1U   /*!< PWM2 A channel: 1 */
#define BOARD_INITFLASH_SEMC_DM0_PIN_NAME                            GPIO_EMC_08   /*!< Pin name */
#define BOARD_INITFLASH_SEMC_DM0_LABEL                                "SEMC_DM0"   /*!< Label */
#define BOARD_INITFLASH_SEMC_DM0_NAME                                 "SEMC_DM0"   /*!< Identifier name */

/* GPIO_SD_B1_07 (coord L4), FlexSPI_CLK */
#define BOARD_INITFLASH_FlexSPI_CLK_PERIPHERAL                           FLEXSPI   /*!< Device name: FLEXSPI */
#define BOARD_INITFLASH_FlexSPI_CLK_SIGNAL                        FLEXSPI_A_SCLK   /*!< FLEXSPI signal: FLEXSPI_A_SCLK */
#define BOARD_INITFLASH_FlexSPI_CLK_PIN_NAME                       GPIO_SD_B1_07   /*!< Pin name */
#define BOARD_INITFLASH_FlexSPI_CLK_LABEL                          "FlexSPI_CLK"   /*!< Label */
#define BOARD_INITFLASH_FlexSPI_CLK_NAME                           "FlexSPI_CLK"   /*!< Identifier name */

/* GPIO_SD_B1_04 (coord P2), FlexSPI_CLK_B */
#define BOARD_INITFLASH_FlexSPI_CLK_B_PERIPHERAL                         FLEXSPI   /*!< Device name: FLEXSPI */
#define BOARD_INITFLASH_FlexSPI_CLK_B_SIGNAL                      FLEXSPI_B_SCLK   /*!< FLEXSPI signal: FLEXSPI_B_SCLK */
#define BOARD_INITFLASH_FlexSPI_CLK_B_PIN_NAME                     GPIO_SD_B1_04   /*!< Pin name */
#define BOARD_INITFLASH_FlexSPI_CLK_B_LABEL                      "FlexSPI_CLK_B"   /*!< Label */
#define BOARD_INITFLASH_FlexSPI_CLK_B_NAME                       "FlexSPI_CLK_B"   /*!< Identifier name */

/* GPIO_SD_B1_08 (coord P3), FlexSPI_D0_A */
#define BOARD_INITFLASH_FlexSPI_D0_A_PERIPHERAL                          FLEXSPI   /*!< Device name: FLEXSPI */
#define BOARD_INITFLASH_FlexSPI_D0_A_SIGNAL                      FLEXSPI_A_DATA0   /*!< FLEXSPI signal: FLEXSPI_A_DATA0 */
#define BOARD_INITFLASH_FlexSPI_D0_A_PIN_NAME                      GPIO_SD_B1_08   /*!< Pin name */
#define BOARD_INITFLASH_FlexSPI_D0_A_LABEL                        "FlexSPI_D0_A"   /*!< Label */
#define BOARD_INITFLASH_FlexSPI_D0_A_NAME                         "FlexSPI_D0_A"   /*!< Identifier name */

/* GPIO_SD_B1_09 (coord N4), FlexSPI_D1_A */
#define BOARD_INITFLASH_FlexSPI_D1_A_PERIPHERAL                          FLEXSPI   /*!< Device name: FLEXSPI */
#define BOARD_INITFLASH_FlexSPI_D1_A_SIGNAL                      FLEXSPI_A_DATA1   /*!< FLEXSPI signal: FLEXSPI_A_DATA1 */
#define BOARD_INITFLASH_FlexSPI_D1_A_PIN_NAME                      GPIO_SD_B1_09   /*!< Pin name */
#define BOARD_INITFLASH_FlexSPI_D1_A_LABEL                        "FlexSPI_D1_A"   /*!< Label */
#define BOARD_INITFLASH_FlexSPI_D1_A_NAME                         "FlexSPI_D1_A"   /*!< Identifier name */

/* GPIO_SD_B1_10 (coord P4), FlexSPI_D2_A */
#define BOARD_INITFLASH_FlexSPI_D2_A_PERIPHERAL                          FLEXSPI   /*!< Device name: FLEXSPI */
#define BOARD_INITFLASH_FlexSPI_D2_A_SIGNAL                      FLEXSPI_A_DATA2   /*!< FLEXSPI signal: FLEXSPI_A_DATA2 */
#define BOARD_INITFLASH_FlexSPI_D2_A_PIN_NAME                      GPIO_SD_B1_10   /*!< Pin name */
#define BOARD_INITFLASH_FlexSPI_D2_A_LABEL                        "FlexSPI_D2_A"   /*!< Label */
#define BOARD_INITFLASH_FlexSPI_D2_A_NAME                         "FlexSPI_D2_A"   /*!< Identifier name */

/* GPIO_SD_B1_11 (coord P5), FlexSPI_D3_A */
#define BOARD_INITFLASH_FlexSPI_D3_A_PERIPHERAL                          FLEXSPI   /*!< Device name: FLEXSPI */
#define BOARD_INITFLASH_FlexSPI_D3_A_SIGNAL                      FLEXSPI_A_DATA3   /*!< FLEXSPI signal: FLEXSPI_A_DATA3 */
#define BOARD_INITFLASH_FlexSPI_D3_A_PIN_NAME                      GPIO_SD_B1_11   /*!< Pin name */
#define BOARD_INITFLASH_FlexSPI_D3_A_LABEL                        "FlexSPI_D3_A"   /*!< Label */
#define BOARD_INITFLASH_FlexSPI_D3_A_NAME                         "FlexSPI_D3_A"   /*!< Identifier name */

/* GPIO_SD_B1_03 (coord M4), FlexSPI_D0_B */
#define BOARD_INITFLASH_FlexSPI_D0_B_PERIPHERAL                          FLEXSPI   /*!< Device name: FLEXSPI */
#define BOARD_INITFLASH_FlexSPI_D0_B_SIGNAL                      FLEXSPI_B_DATA0   /*!< FLEXSPI signal: FLEXSPI_B_DATA0 */
#define BOARD_INITFLASH_FlexSPI_D0_B_PIN_NAME                      GPIO_SD_B1_03   /*!< Pin name */
#define BOARD_INITFLASH_FlexSPI_D0_B_LABEL                        "FlexSPI_D0_B"   /*!< Label */
#define BOARD_INITFLASH_FlexSPI_D0_B_NAME                         "FlexSPI_D0_B"   /*!< Identifier name */

/* GPIO_SD_B1_02 (coord M3), FlexSPI_D1_B */
#define BOARD_INITFLASH_FlexSPI_D1_B_PERIPHERAL                          FLEXSPI   /*!< Device name: FLEXSPI */
#define BOARD_INITFLASH_FlexSPI_D1_B_SIGNAL                      FLEXSPI_B_DATA1   /*!< FLEXSPI signal: FLEXSPI_B_DATA1 */
#define BOARD_INITFLASH_FlexSPI_D1_B_PIN_NAME                      GPIO_SD_B1_02   /*!< Pin name */
#define BOARD_INITFLASH_FlexSPI_D1_B_LABEL                        "FlexSPI_D1_B"   /*!< Label */
#define BOARD_INITFLASH_FlexSPI_D1_B_NAME                         "FlexSPI_D1_B"   /*!< Identifier name */

/* GPIO_SD_B1_01 (coord M5), FlexSPI_D2_B */
#define BOARD_INITFLASH_FlexSPI_D2_B_PERIPHERAL                          FLEXSPI   /*!< Device name: FLEXSPI */
#define BOARD_INITFLASH_FlexSPI_D2_B_SIGNAL                      FLEXSPI_B_DATA2   /*!< FLEXSPI signal: FLEXSPI_B_DATA2 */
#define BOARD_INITFLASH_FlexSPI_D2_B_PIN_NAME                      GPIO_SD_B1_01   /*!< Pin name */
#define BOARD_INITFLASH_FlexSPI_D2_B_LABEL                        "FlexSPI_D2_B"   /*!< Label */
#define BOARD_INITFLASH_FlexSPI_D2_B_NAME                         "FlexSPI_D2_B"   /*!< Identifier name */

/* GPIO_SD_B1_00 (coord L5), FlexSPI_D3_B */
#define BOARD_INITFLASH_FlexSPI_D3_B_PERIPHERAL                          FLEXSPI   /*!< Device name: FLEXSPI */
#define BOARD_INITFLASH_FlexSPI_D3_B_SIGNAL                      FLEXSPI_B_DATA3   /*!< FLEXSPI signal: FLEXSPI_B_DATA3 */
#define BOARD_INITFLASH_FlexSPI_D3_B_PIN_NAME                      GPIO_SD_B1_00   /*!< Pin name */
#define BOARD_INITFLASH_FlexSPI_D3_B_LABEL                        "FlexSPI_D3_B"   /*!< Label */
#define BOARD_INITFLASH_FlexSPI_D3_B_NAME                         "FlexSPI_D3_B"   /*!< Identifier name */

/* GPIO_SD_B1_05 (coord N3), FlexSPI_DQS */
#define BOARD_INITFLASH_FlexSPI_DQS_PERIPHERAL                           FLEXSPI   /*!< Device name: FLEXSPI */
#define BOARD_INITFLASH_FlexSPI_DQS_SIGNAL                         FLEXSPI_A_DQS   /*!< FLEXSPI signal: FLEXSPI_A_DQS */
#define BOARD_INITFLASH_FlexSPI_DQS_PIN_NAME                       GPIO_SD_B1_05   /*!< Pin name */
#define BOARD_INITFLASH_FlexSPI_DQS_LABEL                          "FlexSPI_DQS"   /*!< Label */
#define BOARD_INITFLASH_FlexSPI_DQS_NAME                           "FlexSPI_DQS"   /*!< Identifier name */

/* GPIO_SD_B1_06 (coord L3), FlexSPI_SS0 */
#define BOARD_INITFLASH_FlexSPI_SS0_PERIPHERAL                           FLEXSPI   /*!< Device name: FLEXSPI */
#define BOARD_INITFLASH_FlexSPI_SS0_SIGNAL                       FLEXSPI_A_SS0_B   /*!< FLEXSPI signal: FLEXSPI_A_SS0_B */
#define BOARD_INITFLASH_FlexSPI_SS0_PIN_NAME                       GPIO_SD_B1_06   /*!< Pin name */
#define BOARD_INITFLASH_FlexSPI_SS0_LABEL                          "FlexSPI_SS0"   /*!< Label */
#define BOARD_INITFLASH_FlexSPI_SS0_NAME                           "FlexSPI_SS0"   /*!< Identifier name */

/* GPIO_AD_B0_05 (coord G14), Flash_RST */
#define BOARD_INITFLASH_CAN_STBY_GPIO                                      GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITFLASH_CAN_STBY_PORT                                      GPIO1   /*!< PORT device name: GPIO1 */
#define BOARD_INITFLASH_CAN_STBY_GPIO_PIN                                     5U   /*!< GPIO1 pin index: 5 */
#define BOARD_INITFLASH_CAN_STBY_PIN_NAME                          GPIO_AD_B0_05   /*!< Pin name */
#define BOARD_INITFLASH_CAN_STBY_LABEL                               "Flash_RST"   /*!< Label */
#define BOARD_INITFLASH_CAN_STBY_NAME                                 "CAN_STBY"   /*!< Identifier name */
#define BOARD_INITFLASH_CAN_STBY_DIRECTION              kPIN_MUX_DirectionOutput   /*!< Direction */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitFlash(void);

/* GPIO_AD_B0_11 (coord G10), JTAG_nTRST/J21[3]/INT2_COMBO/LCD_TOUCH_INT/J22[3]/U32[9] */
#define BOARD_INITTJTAG_INT2_COMBO_PERIPHERAL                               JTAG   /*!< Device name: JTAG */
#define BOARD_INITTJTAG_INT2_COMBO_SIGNAL                                  TRSTB   /*!< JTAG signal: TRSTB */
#define BOARD_INITTJTAG_INT2_COMBO_PIN_NAME                        GPIO_AD_B0_11   /*!< Pin name */
#define BOARD_INITTJTAG_INT2_COMBO_LABEL "JTAG_nTRST/J21[3]/INT2_COMBO/LCD_TOUCH_INT/J22[3]/U32[9]" /*!< Label */
#define BOARD_INITTJTAG_INT2_COMBO_NAME                             "INT2_COMBO"   /*!< Identifier name */

/* GPIO_AD_B0_10 (coord G13), JTAG_TDO/J21[13]/INT1_COMBO/ENET_INT/J22[6]/U32[11] */
#define BOARD_INITTJTAG_INT1_COMBO_PERIPHERAL                               JTAG   /*!< Device name: JTAG */
#define BOARD_INITTJTAG_INT1_COMBO_SIGNAL                                    TDO   /*!< JTAG signal: TDO */
#define BOARD_INITTJTAG_INT1_COMBO_PIN_NAME                        GPIO_AD_B0_10   /*!< Pin name */
#define BOARD_INITTJTAG_INT1_COMBO_LABEL "JTAG_TDO/J21[13]/INT1_COMBO/ENET_INT/J22[6]/U32[11]" /*!< Label */
#define BOARD_INITTJTAG_INT1_COMBO_NAME                             "INT1_COMBO"   /*!< Identifier name */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InittJtag(void);


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLPI2C(void);

/* GPIO_AD_B1_12 (coord H12), SAI1_RXD/CSI_D5/J35[5]/U13[16] */
#define BOARD_INITLPSPI_CSI_D5_PERIPHERAL                                 LPSPI3   /*!< Device name: LPSPI3 */
#define BOARD_INITLPSPI_CSI_D5_SIGNAL                                       PCS0   /*!< LPSPI3 signal: PCS0 */
#define BOARD_INITLPSPI_CSI_D5_PIN_NAME                            GPIO_AD_B1_12   /*!< Pin name */
#define BOARD_INITLPSPI_CSI_D5_LABEL            "SAI1_RXD/CSI_D5/J35[5]/U13[16]"   /*!< Label */
#define BOARD_INITLPSPI_CSI_D5_NAME                                     "CSI_D5"   /*!< Identifier name */

/* GPIO_AD_B1_15 (coord J14), SAI1_TX_SYNC/CSI_D2/J35[6]/U13[13] */
#define BOARD_INITLPSPI_CSI_D2_PERIPHERAL                                 LPSPI3   /*!< Device name: LPSPI3 */
#define BOARD_INITLPSPI_CSI_D2_SIGNAL                                        SCK   /*!< LPSPI3 signal: SCK */
#define BOARD_INITLPSPI_CSI_D2_PIN_NAME                            GPIO_AD_B1_15   /*!< Pin name */
#define BOARD_INITLPSPI_CSI_D2_LABEL        "SAI1_TX_SYNC/CSI_D2/J35[6]/U13[13]"   /*!< Label */
#define BOARD_INITLPSPI_CSI_D2_NAME                                     "CSI_D2"   /*!< Identifier name */

/* GPIO_AD_B1_13 (coord H11), SAI1_TXD/CSI_D4/J35[3]/U13[14] */
#define BOARD_INITLPSPI_CSI_D4_PERIPHERAL                                 LPSPI3   /*!< Device name: LPSPI3 */
#define BOARD_INITLPSPI_CSI_D4_SIGNAL                                        SDI   /*!< LPSPI3 signal: SDI */
#define BOARD_INITLPSPI_CSI_D4_PIN_NAME                            GPIO_AD_B1_13   /*!< Pin name */
#define BOARD_INITLPSPI_CSI_D4_LABEL            "SAI1_TXD/CSI_D4/J35[3]/U13[14]"   /*!< Label */
#define BOARD_INITLPSPI_CSI_D4_NAME                                     "CSI_D4"   /*!< Identifier name */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLPSPI(void);


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLPUART(void);

/* GPIO_AD_B0_04 (coord F11), BOOT_MODE[0] */
#define BOARD_INITBOOTPIN_CSI_PWDN_GPIO                                    GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITBOOTPIN_CSI_PWDN_PORT                                    GPIO1   /*!< PORT device name: GPIO1 */
#define BOARD_INITBOOTPIN_CSI_PWDN_GPIO_PIN                                   4U   /*!< GPIO1 pin index: 4 */
#define BOARD_INITBOOTPIN_CSI_PWDN_PIN_NAME                        GPIO_AD_B0_04   /*!< Pin name */
#define BOARD_INITBOOTPIN_CSI_PWDN_LABEL                          "BOOT_MODE[0]"   /*!< Label */
#define BOARD_INITBOOTPIN_CSI_PWDN_NAME                               "CSI_PWDN"   /*!< Identifier name */
#define BOARD_INITBOOTPIN_CSI_PWDN_DIRECTION            kPIN_MUX_DirectionOutput   /*!< Direction */

/* GPIO_B1_15 (coord B14), USB_HOST_PWR */
#define BOARD_INITBOOTPIN_BACKLIGHT_CTL_GPIO                               GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITBOOTPIN_BACKLIGHT_CTL_PORT                               GPIO2   /*!< PORT device name: GPIO2 */
#define BOARD_INITBOOTPIN_BACKLIGHT_CTL_GPIO_PIN                             31U   /*!< GPIO2 pin index: 31 */
#define BOARD_INITBOOTPIN_BACKLIGHT_CTL_PIN_NAME                      GPIO_B1_15   /*!< Pin name */
#define BOARD_INITBOOTPIN_BACKLIGHT_CTL_LABEL                     "USB_HOST_PWR"   /*!< Label */
#define BOARD_INITBOOTPIN_BACKLIGHT_CTL_NAME                     "BACKLIGHT_CTL"   /*!< Identifier name */
#define BOARD_INITBOOTPIN_BACKLIGHT_CTL_DIRECTION       kPIN_MUX_DirectionOutput   /*!< Direction */

/* GPIO_B1_14 (coord C14), SD0_VSELECT */
#define BOARD_INITBOOTPIN_SD0_VSELECT_GPIO                                 GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITBOOTPIN_SD0_VSELECT_PORT                                 GPIO2   /*!< PORT device name: GPIO2 */
#define BOARD_INITBOOTPIN_SD0_VSELECT_GPIO_PIN                               30U   /*!< GPIO2 pin index: 30 */
#define BOARD_INITBOOTPIN_SD0_VSELECT_PIN_NAME                        GPIO_B1_14   /*!< Pin name */
#define BOARD_INITBOOTPIN_SD0_VSELECT_LABEL                        "SD0_VSELECT"   /*!< Label */
#define BOARD_INITBOOTPIN_SD0_VSELECT_NAME                         "SD0_VSELECT"   /*!< Identifier name */
#define BOARD_INITBOOTPIN_SD0_VSELECT_DIRECTION         kPIN_MUX_DirectionOutput   /*!< Direction */

/* GPIO_AD_B0_14 (coord H14), CAN2_TX/U12[1] */
#define BOARD_INITBOOTPIN_CAN2_TX_PERIPHERAL                             LPUART1   /*!< Device name: LPUART1 */
#define BOARD_INITBOOTPIN_CAN2_TX_SIGNAL                                   CTS_B   /*!< LPUART1 signal: CTS_B */
#define BOARD_INITBOOTPIN_CAN2_TX_PIN_NAME                         GPIO_AD_B0_14   /*!< Pin name */
#define BOARD_INITBOOTPIN_CAN2_TX_LABEL                         "CAN2_TX/U12[1]"   /*!< Label */
#define BOARD_INITBOOTPIN_CAN2_TX_NAME                                 "CAN2_TX"   /*!< Identifier name */

/* GPIO_AD_B0_15 (coord L10), CAN2_RX/U12[4] */
#define BOARD_INITBOOTPIN_CAN2_RX_PERIPHERAL                             LPUART1   /*!< Device name: LPUART1 */
#define BOARD_INITBOOTPIN_CAN2_RX_SIGNAL                                   RTS_B   /*!< LPUART1 signal: RTS_B */
#define BOARD_INITBOOTPIN_CAN2_RX_PIN_NAME                         GPIO_AD_B0_15   /*!< Pin name */
#define BOARD_INITBOOTPIN_CAN2_RX_LABEL                         "CAN2_RX/U12[4]"   /*!< Label */
#define BOARD_INITBOOTPIN_CAN2_RX_NAME                                 "CAN2_RX"   /*!< Identifier name */

/* GPIO_AD_B0_13 (coord L14), UART1_RXD */
#define BOARD_INITBOOTPIN_UART1_RXD_PERIPHERAL                           LPUART1   /*!< Device name: LPUART1 */
#define BOARD_INITBOOTPIN_UART1_RXD_SIGNAL                                    RX   /*!< LPUART1 signal: RX */
#define BOARD_INITBOOTPIN_UART1_RXD_PIN_NAME                       GPIO_AD_B0_13   /*!< Pin name */
#define BOARD_INITBOOTPIN_UART1_RXD_LABEL                            "UART1_RXD"   /*!< Label */
#define BOARD_INITBOOTPIN_UART1_RXD_NAME                             "UART1_RXD"   /*!< Identifier name */

/* GPIO_AD_B0_12 (coord K14), UART1_TXD */
#define BOARD_INITBOOTPIN_UART1_TXD_PERIPHERAL                           LPUART1   /*!< Device name: LPUART1 */
#define BOARD_INITBOOTPIN_UART1_TXD_SIGNAL                                    TX   /*!< LPUART1 signal: TX */
#define BOARD_INITBOOTPIN_UART1_TXD_PIN_NAME                       GPIO_AD_B0_12   /*!< Pin name */
#define BOARD_INITBOOTPIN_UART1_TXD_LABEL                            "UART1_TXD"   /*!< Label */
#define BOARD_INITBOOTPIN_UART1_TXD_NAME                             "UART1_TXD"   /*!< Identifier name */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitBootPin(void);

/* WAKEUP (coord L6), SD_PWREN */
#define BOARD_INITWIFI_SD_PWREN_GPIO                                       GPIO5   /*!< GPIO device name: GPIO5 */
#define BOARD_INITWIFI_SD_PWREN_PORT                                       GPIO5   /*!< PORT device name: GPIO5 */
#define BOARD_INITWIFI_SD_PWREN_GPIO_PIN                                      0U   /*!< GPIO5 pin index: 0 */
#define BOARD_INITWIFI_SD_PWREN_PIN_NAME                                  WAKEUP   /*!< Pin name */
#define BOARD_INITWIFI_SD_PWREN_LABEL                                 "SD_PWREN"   /*!< Label */
#define BOARD_INITWIFI_SD_PWREN_NAME                                  "SD_PWREN"   /*!< Identifier name */
#define BOARD_INITWIFI_SD_PWREN_DIRECTION                kPIN_MUX_DirectionInput   /*!< Direction */

/* PMIC_ON_REQ (coord K7), PMIC_ON_REQ */
#define BOARD_INITWIFI_PMIC_ON_REQ_GPIO                                    GPIO5   /*!< GPIO device name: GPIO5 */
#define BOARD_INITWIFI_PMIC_ON_REQ_PORT                                    GPIO5   /*!< PORT device name: GPIO5 */
#define BOARD_INITWIFI_PMIC_ON_REQ_GPIO_PIN                                   1U   /*!< GPIO5 pin index: 1 */
#define BOARD_INITWIFI_PMIC_ON_REQ_PIN_NAME                          PMIC_ON_REQ   /*!< Pin name */
#define BOARD_INITWIFI_PMIC_ON_REQ_LABEL                           "PMIC_ON_REQ"   /*!< Label */
#define BOARD_INITWIFI_PMIC_ON_REQ_NAME                            "PMIC_ON_REQ"   /*!< Identifier name */
#define BOARD_INITWIFI_PMIC_ON_REQ_DIRECTION            kPIN_MUX_DirectionOutput   /*!< Direction */

/* GPIO_SD_B0_01 (coord J3), SD1_CLK/J24[3] */
#define BOARD_INITWIFI_SD1_CLK_PERIPHERAL                                 USDHC1   /*!< Device name: USDHC1 */
#define BOARD_INITWIFI_SD1_CLK_SIGNAL                                  usdhc_clk   /*!< USDHC1 signal: usdhc_clk */
#define BOARD_INITWIFI_SD1_CLK_PIN_NAME                            GPIO_SD_B0_01   /*!< Pin name */
#define BOARD_INITWIFI_SD1_CLK_LABEL                            "SD1_CLK/J24[3]"   /*!< Label */
#define BOARD_INITWIFI_SD1_CLK_NAME                                    "SD1_CLK"   /*!< Identifier name */

/* GPIO_SD_B0_03 (coord K1), SD1_D1/J24[5]/SPI_MISO */
#define BOARD_INITWIFI_SD1_D1_PERIPHERAL                                  USDHC1   /*!< Device name: USDHC1 */
#define BOARD_INITWIFI_SD1_D1_SIGNAL                                  usdhc_data   /*!< USDHC1 signal: usdhc_data */
#define BOARD_INITWIFI_SD1_D1_CHANNEL                                         1U   /*!< USDHC1 usdhc_data channel: 1 */
#define BOARD_INITWIFI_SD1_D1_PIN_NAME                             GPIO_SD_B0_03   /*!< Pin name */
#define BOARD_INITWIFI_SD1_D1_LABEL                     "SD1_D1/J24[5]/SPI_MISO"   /*!< Label */
#define BOARD_INITWIFI_SD1_D1_NAME                                      "SD1_D1"   /*!< Identifier name */

/* GPIO_SD_B0_02 (coord J1), SD1_D0/J24[4]/SPI_MOSI/PWM */
#define BOARD_INITWIFI_SD1_D0_PERIPHERAL                                  USDHC1   /*!< Device name: USDHC1 */
#define BOARD_INITWIFI_SD1_D0_SIGNAL                                  usdhc_data   /*!< USDHC1 signal: usdhc_data */
#define BOARD_INITWIFI_SD1_D0_CHANNEL                                         0U   /*!< USDHC1 usdhc_data channel: 0 */
#define BOARD_INITWIFI_SD1_D0_PIN_NAME                             GPIO_SD_B0_02   /*!< Pin name */
#define BOARD_INITWIFI_SD1_D0_LABEL                 "SD1_D0/J24[4]/SPI_MOSI/PWM"   /*!< Label */
#define BOARD_INITWIFI_SD1_D0_NAME                                      "SD1_D0"   /*!< Identifier name */

/* GPIO_SD_B0_04 (coord H2), SD1_D2 */
#define BOARD_INITWIFI_SD1_D2_PERIPHERAL                                  USDHC1   /*!< Device name: USDHC1 */
#define BOARD_INITWIFI_SD1_D2_SIGNAL                                  usdhc_data   /*!< USDHC1 signal: usdhc_data */
#define BOARD_INITWIFI_SD1_D2_CHANNEL                                         2U   /*!< USDHC1 usdhc_data channel: 2 */
#define BOARD_INITWIFI_SD1_D2_PIN_NAME                             GPIO_SD_B0_04   /*!< Pin name */
#define BOARD_INITWIFI_SD1_D2_LABEL                                     "SD1_D2"   /*!< Label */
#define BOARD_INITWIFI_SD1_D2_NAME                                      "SD1_D2"   /*!< Identifier name */

/* GPIO_SD_B0_05 (coord J2), SD1_D3 */
#define BOARD_INITWIFI_SD1_D3_PERIPHERAL                                  USDHC1   /*!< Device name: USDHC1 */
#define BOARD_INITWIFI_SD1_D3_SIGNAL                                  usdhc_data   /*!< USDHC1 signal: usdhc_data */
#define BOARD_INITWIFI_SD1_D3_CHANNEL                                         3U   /*!< USDHC1 usdhc_data channel: 3 */
#define BOARD_INITWIFI_SD1_D3_PIN_NAME                             GPIO_SD_B0_05   /*!< Pin name */
#define BOARD_INITWIFI_SD1_D3_LABEL                                     "SD1_D3"   /*!< Label */
#define BOARD_INITWIFI_SD1_D3_NAME                                      "SD1_D3"   /*!< Identifier name */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitWifi(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */
#endif

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
